# Generated by Django 3.2 on 2021-05-07 10:17

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emplyoee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='any name of the company', max_length=50)),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('address', models.CharField(default='SOME STRING', max_length=100)),
                ('website', models.CharField(default='website name', max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GST_Treatment', models.CharField(choices=[('item_key1', 'Item title 1.1'), ('item_key2', 'Item title 1.2'), ('item_key3', 'Item title 1.3')], max_length=50)),
                ('Tax_preference', models.CharField(choices=[('1', 'Taxable'), ('2', 'Tax Exempt')], default='1', max_length=20)),
            ],
        ),
    ]
