# Generated by Django 3.2 on 2021-05-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherdetails',
            name='Currency',
            field=models.CharField(choices=[('1', 'USD'), ('2', 'Indian-Rupee'), ('3', 'Euro'), ('4', 'Dinar'), ('5', 'Dirham'), ('6', 'Yuan')], default='2', max_length=50),
        ),
        migrations.AddField(
            model_name='otherdetails',
            name='Place_of_supply',
            field=models.CharField(choices=[('1', 'Delhi'), ('2', 'UP'), ('3', 'Uk'), ('4', 'J&K'), ('5', 'Harayana'), ('6', 'Punjab'), ('7', 'Gujarat'), ('8', 'MP'), ('9', 'Maharashtra'), ('10', 'Telangana'), ('11', 'AP'), ('12', 'Bihar'), ('13', 'Jharkhand'), ('14', 'WB'), ('15', 'Assam'), ('16', 'Karnataka'), ('17', 'kerala'), ('18', 'TamilNadu'), ('19', 'Goa'), ('20', 'Manipur'), ('21', 'Sikkim'), ('22', 'Nagaland'), ('23', 'Mizoram'), ('24', 'Meghalaya')], default='1', max_length=50),
        ),
    ]
