# Generated by Django 3.2 on 2021-05-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210507_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emplyoee',
            name='created',
        ),
        migrations.AddField(
            model_name='emplyoee',
            name='Currency',
            field=models.CharField(choices=[('1', 'USD'), ('2', 'Indian-Rupee'), ('3', 'Euro'), ('4', 'Dinar'), ('5', 'Dirham'), ('6', 'Yuan')], default='2', max_length=50),
        ),
        migrations.AddField(
            model_name='emplyoee',
            name='GST_Treatment',
            field=models.CharField(choices=[('item_key1', 'Item title 1.1'), ('item_key2', 'Item title 1.2'), ('item_key3', 'Item title 1.3')], default='item_key1', max_length=50),
        ),
        migrations.AddField(
            model_name='emplyoee',
            name='Place_of_supply',
            field=models.CharField(choices=[('1', 'Delhi'), ('2', 'UP'), ('3', 'Uk'), ('4', 'J&K'), ('5', 'Harayana'), ('6', 'Punjab'), ('7', 'Gujarat'), ('8', 'MP'), ('9', 'Maharashtra'), ('10', 'Telangana'), ('11', 'AP'), ('12', 'Bihar'), ('13', 'Jharkhand'), ('14', 'WB'), ('15', 'Assam'), ('16', 'Karnataka'), ('17', 'kerala'), ('18', 'TamilNadu'), ('19', 'Goa'), ('20', 'Manipur'), ('21', 'Sikkim'), ('22', 'Nagaland'), ('23', 'Mizoram'), ('24', 'Meghalaya')], default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='emplyoee',
            name='Tax_preference',
            field=models.CharField(choices=[('1', 'Taxable'), ('2', 'Tax Exempt')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='emplyoee',
            name='remarks',
            field=models.TextField(default='any thing to say..', max_length=300),
        ),
    ]
