# Generated by Django 3.2 on 2021-05-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20210509_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemgroup',
            name='Brand',
            field=models.CharField(choices=[('etc', 'etc'), (' ', ' ')], default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='itemgroup',
            name='Discription',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemgroup',
            name='Manufracturer',
            field=models.CharField(choices=[('abc', 'ABC'), ('Xyz', 'XYZ')], default='abc', max_length=20),
        ),
        migrations.AddField(
            model_name='itemgroup',
            name='Tax_preference',
            field=models.CharField(choices=[('1', 'Taxable'), ('2', 'Tax Exempt')], default='1', max_length=20),
        ),
    ]
