# Generated by Django 3.2 on 2021-05-10 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20210509_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invoice_prefix', models.CharField(editable=False, max_length=36, unique=True)),
                ('Customer_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='customer.emplyoee', verbose_name='fullname')),
            ],
        ),
    ]
